# Generated by Django 6.0 on 2025-12-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('MANAGER', 'Manager')], default='MANAGER', max_length=20),
        ),
    ]
