# Generated by Django 5.2.8 on 2025-11-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='unit',
            field=models.CharField(default='portion', help_text='portion, plate, glass, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Rice, Noodles, Drinks', max_length=100),
        ),
    ]
