# Generated by Django 5.2.8 on 2025-12-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_menuitem_unit_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrecord',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date for perishable ingredients', null=True),
        ),
    ]
