# Generated by Django 5.2.8 on 2025-12-22 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryrecord_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientDailyDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_date', models.DateField()),
                ('quantity', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.store')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'ingredient', 'demand_date'), name='unique_daily_ingredient_demand')],
            },
        ),
    ]
