# Generated by Django 5.2.8 on 2025-12-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_ingredientdailydemand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='channel',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email')], max_length=20),
        ),
    ]
