# Generated by Django 6.0 on 2025-12-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('VOID', 'Void'), ('DRAF', 'Draf')], default='DRAF', max_length=10),
        ),
    ]
