# Generated by Django 6.0 on 2026-01-01 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='import_ref',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sold_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
